"""add image to containers db

Revision ID: 24b2acc645b3
Revises: cd8c2f9a2146
Create Date: 2020-09-17 22:13:12.193213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b2acc645b3'
down_revision = 'cd8c2f9a2146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'image')
    # ### end Alembic commands ###
